import React from 'react';
import { SlideContent } from '../types';

interface SlideProps {
  data: SlideContent;
  totalSlides: number;
  currentSlide: number;
  isActive: boolean;
}

const Slide: React.FC<SlideProps> = ({ data, totalSlides, currentSlide, isActive }) => {
  if (!isActive) return null;

  return (
    <div className="w-full h-full flex flex-col justify-between p-8 md:p-16 animate-fade-in relative overflow-hidden">
      
      {/* Background Decorative Elements */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl translate-y-1/2 -translate-x-1/2 pointer-events-none"></div>

      {/* Header */}
      <header className="z-10">
        <h2 className="text-4xl md:text-6xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-200 to-purple-200 mb-6 leading-tight">
          {data.title}
        </h2>
        <div className="h-1 w-24 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full"></div>
      </header>

      {/* Body */}
      <main className="flex-grow flex flex-col justify-center z-10 my-8">
        <ul className="space-y-6">
          {data.points.map((point, idx) => (
            <li key={idx} className="flex items-start text-base md:text-xl text-slate-200 font-light tracking-wide leading-relaxed">
              <span className="inline-block w-2 h-2 mt-2.5 mr-4 bg-blue-400 rounded-full flex-shrink-0" />
              <span>{point}</span>
            </li>
          ))}
        </ul>
      </main>

      {/* Footer / Key Message */}
      <footer className="z-10 border-t border-slate-700 pt-8 mt-4">
        <div className="bg-slate-800/50 p-6 rounded-xl border-l-4 border-yellow-400 backdrop-blur-sm">
          <p className="text-yellow-200 text-lg md:text-xl font-medium italic">
            "{data.keyMessage}"
          </p>
        </div>
        <div className="mt-4 text-slate-500 text-sm flex justify-between items-center">
           <span>Generated by Gemini 2.5</span>
           <span>{currentSlide + 1} / {totalSlides}</span>
        </div>
      </footer>
    </div>
  );
};

export default Slide;